require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;
const API_KEY = process.env.GEMINI_API_KEY;

app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname)));

// ── Models to try in order ──
const MODELS = [
  'gemini-1.5-flash',
  'gemini-1.5-flash-8b',
  'gemini-2.0-flash-lite',
  'gemini-2.0-flash',
  'gemini-1.5-pro',
  'gemini-pro'
];

// ── Prompts ──
const PROMPTS = {
  full: `You are a helpful and friendly study assistant for Indian students preparing for school and college exams.
Analyze the following study material and provide a well-structured summary.

Format your response exactly like this:

📌 KEY CONCEPTS
(List the 5–8 most important concepts from the content)

📖 IMPORTANT DEFINITIONS
(Define key terms in simple, easy-to-understand language)

🔁 QUICK REVISION POINTS
(8–10 bullet points of the most important facts to remember)

💡 IMPORTANT TO REMEMBER
(2–3 critical points students often miss or get wrong in exams)

Keep the language simple, clear, and suitable for Indian school/college students.`,

  exam: `You are an experienced Indian teacher helping students prepare for board exams and competitive exams.
Based on the study material below, generate exam preparation content.

Format your response exactly like this:

⭐ MOST IMPORTANT TOPICS (must study these)

❓ SHORT ANSWER QUESTIONS (2–3 marks)
(List 5 questions with brief answers)

📝 LONG ANSWER QUESTIONS (5 marks)
(List 3 questions with detailed answers)

🔥 MOST LIKELY TO APPEAR IN EXAM
(Top 3 topics/questions that are most likely to be asked)

💯 SCORING TIPS
(How to write answers to score maximum marks)`,

  short: `Summarize the following study material into exactly 10 clear, concise bullet points.
Each point should be one powerful sentence capturing the most important fact.
Number them 1–10. Use simple English suitable for a student.
Focus only on the most exam-relevant information.`,

  simple: `You are a friendly teacher explaining a topic to a 15-year-old student in India.
Use very simple everyday language, relatable examples from Indian daily life,
short paragraphs with clear headings, and a friendly encouraging tone.`,

  mindmap: `Create a structured mind map in text format from the following study content.
Use tree format with ├── and └── symbols. Make it comprehensive.`
};

// ── Demo responses (used when API is unavailable) ──
const DEMO = {
  full: `📌 KEY CONCEPTS

1. Atomic Structure — Atoms consist of protons, neutrons, and electrons. The nucleus contains protons (+) and neutrons (neutral), while electrons (-) orbit in shells.

2. Chemical Bonding — Atoms bond to achieve stable electron configurations. Ionic bonds involve electron transfer; covalent bonds involve electron sharing.

3. States of Matter — Solids (fixed shape/volume), Liquids (fixed volume, variable shape), Gases (variable shape/volume). Changes of state involve energy exchange.

4. Newton's Laws of Motion — (1) Inertia: objects stay at rest/motion unless acted on; (2) F=ma; (3) Every action has equal and opposite reaction.

5. Cell Biology — The cell is the basic unit of life. Plant cells have cell walls and chloroplasts; animal cells have centrioles. Mitochondria = powerhouse.

📖 IMPORTANT DEFINITIONS

• Atom: Smallest unit of an element that retains its chemical properties
• Molecule: Two or more atoms bonded together
• Osmosis: Movement of water from low to high solute concentration through a semi-permeable membrane
• Photosynthesis: Process by which plants convert CO₂ + H₂O + sunlight → glucose + O₂
• Acceleration: Rate of change of velocity (m/s²)

🔁 QUICK REVISION POINTS

• The atomic number = number of protons = number of electrons (in neutral atom)
• Valence electrons determine chemical reactivity
• pH scale: 0–6 = acidic, 7 = neutral, 8–14 = basic/alkaline
• Kinetic energy = ½mv²; Potential energy = mgh
• DNA carries genetic information; RNA transfers it for protein synthesis
• Mitosis = cell division for growth; Meiosis = cell division for reproduction
• Newton's second law: Force = Mass × Acceleration
• The speed of light = 3 × 10⁸ m/s

💡 IMPORTANT TO REMEMBER

⚠️ Students often confuse mass and weight — mass is constant, weight changes with gravity (W = mg)

⚠️ In chemical equations, atoms must be balanced on both sides — check this carefully in exams

⚠️ Photosynthesis occurs in chloroplasts (in leaves), not the entire plant cell

━━━━━━━━━━━━━━━━━━━━━━━━
🎯 This is a DEMO summary generated by NoteSnap.
Upload your own PDF and use a valid Gemini API key for real AI-powered summaries!`,

  exam: `⭐ MOST IMPORTANT TOPICS (must study these)

→ Laws of Motion and Applications
→ Atomic Structure and Chemical Bonding
→ Cell Structure and Functions
→ Photosynthesis and Respiration
→ Electricity and Magnetism

❓ SHORT ANSWER QUESTIONS (2–3 marks)

Q1. What is Newton's Second Law of Motion?
Ans: Newton's Second Law states that Force = Mass × Acceleration (F = ma). The acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass.

Q2. Differentiate between Mitosis and Meiosis.
Ans: Mitosis produces 2 identical daughter cells (for growth/repair); Meiosis produces 4 genetically different cells (for reproduction). Mitosis maintains chromosome number; Meiosis halves it.

Q3. What is the difference between ionic and covalent bonding?
Ans: Ionic bonding involves transfer of electrons between atoms (e.g., NaCl). Covalent bonding involves sharing of electrons (e.g., H₂O). Ionic compounds have high melting points; covalent compounds generally have lower melting points.

Q4. Define osmosis with an example.
Ans: Osmosis is the movement of water molecules from a region of low solute concentration to high solute concentration through a semi-permeable membrane. Example: Water absorption by plant roots from soil.

Q5. What is the role of mitochondria in a cell?
Ans: Mitochondria are the powerhouse of the cell. They produce ATP (energy) through cellular respiration using glucose and oxygen. They have their own DNA and can self-replicate.

📝 LONG ANSWER QUESTIONS (5 marks)

Q1. Explain the process of Photosynthesis with the chemical equation.
Q2. Describe Newton's Three Laws of Motion with real-life examples.
Q3. Explain atomic structure and how it determines chemical properties.

🔥 MOST LIKELY TO APPEAR IN EXAM

1. ⭐ Newton's Laws — numerical problems on F=ma
2. ⭐ Cell structure diagram — labelling and functions
3. ⭐ Chemical bonding — ionic vs covalent with examples

💯 SCORING TIPS

✓ Always write the formula first before solving numericals
✓ Draw labeled diagrams wherever possible — they earn extra marks
✓ Use bullet points for definitions — clearer and easier to mark
✓ Write the SI unit after every numerical answer

━━━━━━━━━━━━━━━━━━━━━━━━
🎯 DEMO output — upload your PDF for real AI exam prep!`,

  short: `1. The cell is the basic structural and functional unit of all living organisms.
2. Newton's First Law states that an object at rest stays at rest unless acted upon by an external force.
3. Photosynthesis converts carbon dioxide and water into glucose using sunlight energy.
4. The atomic number of an element equals the number of protons in its nucleus.
5. Chemical reactions involve breaking and forming of chemical bonds between atoms.
6. Osmosis is the diffusion of water across a semi-permeable membrane from low to high solute concentration.
7. DNA (deoxyribonucleic acid) carries the genetic information of all living organisms.
8. Force equals mass multiplied by acceleration (F = ma) — Newton's Second Law.
9. Mitochondria produce ATP through cellular respiration — they are the powerhouse of the cell.
10. The speed of light in vacuum is approximately 3 × 10⁸ metres per second.

━━━━━━━━━━━━━━━━━━━━
🎯 DEMO summary — upload your PDF for real AI-generated revision points!`,

  simple: `Hey! Let me explain this like your best friend would 😊

🌟 What's the Big Idea?

Think of science like a giant puzzle. Everything around you — your phone, your food, your body — is made of tiny tiny pieces called atoms. They're so small that millions of them fit on the tip of a pencil!

⚡ Why Do Things Move?

You know how a cricket ball keeps going after it's hit? That's because of something called inertia — objects like to keep doing what they're doing. Sir Isaac Newton figured this out! He said:
- If something is resting, it stays resting (lazy, right? 😄)
- If something is moving, it keeps moving
- Unless something pushes or pulls it

🌿 How Do Plants Eat?

Plants are literally solar-powered! They take:
☀️ Sunlight + 💧 Water + 💨 Carbon dioxide (what we breathe out)
...and turn it into sugar (their food) + Oxygen (what we breathe in!)
That's why trees are so important — they give us the air we breathe!

🔬 What's Inside Us?

Your body is made of about 37 TRILLION cells — each one like a tiny city with its own power plant (mitochondria), control centre (nucleus), and walls (cell membrane). Cool, right?

━━━━━━━━━━━━━━━━━━━━
🎯 DEMO explanation — upload your PDF for real simplified summaries!`,

  mindmap: `🗺️ SCIENCE — MAIN TOPICS
  │
  ├── 🔬 Biology
  │     ├── Cell Theory
  │     │     ├── Cell is basic unit of life
  │     │     ├── Plant cell: cell wall, chloroplast, large vacuole
  │     │     └── Animal cell: centrioles, small vacuoles
  │     ├── Processes
  │     │     ├── Photosynthesis: CO₂ + H₂O → Glucose + O₂
  │     │     ├── Respiration: Glucose + O₂ → CO₂ + H₂O + ATP
  │     │     └── Osmosis: water movement across membrane
  │     └── Genetics
  │           ├── DNA → RNA → Protein
  │           ├── Mitosis: growth, 2 identical cells
  │           └── Meiosis: reproduction, 4 unique cells
  │
  ├── ⚛️ Physics
  │     ├── Newton's Laws
  │     │     ├── 1st: Inertia
  │     │     ├── 2nd: F = ma
  │     │     └── 3rd: Action-Reaction
  │     ├── Energy
  │     │     ├── KE = ½mv²
  │     │     └── PE = mgh
  │     └── Light & Sound
  │           ├── Speed of light = 3×10⁸ m/s
  │           └── Sound needs medium to travel
  │
  └── 🧪 Chemistry
        ├── Atomic Structure
        │     ├── Protons (nucleus, +charge)
        │     ├── Neutrons (nucleus, neutral)
        │     └── Electrons (orbits, -charge)
        ├── Bonding
        │     ├── Ionic: electron transfer (NaCl)
        │     └── Covalent: electron sharing (H₂O)
        └── Reactions
              ├── Endothermic: absorbs heat
              └── Exothermic: releases heat

━━━━━━━━━━━━━━━━━━━━━━━━
🎯 DEMO mind map — upload your PDF for a real topic tree!`
};

// ── Try a single model ──
async function tryModel(modelName, prompt) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${API_KEY}`;
  const body = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: { temperature: 0.35, maxOutputTokens: 2000 }
  };

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });

  const data = await res.json();

  if (data.error) {
    console.log(`  ✗ ${modelName}: ${data.error.message.substring(0, 80)}`);
    return null;
  }

  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) return null;

  return { text, model: modelName };
}

// ── Main summarize endpoint ──
app.post('/api/summarize', async (req, res) => {
  const { text, type, subject, demo } = req.body;

  // ── Demo mode ──
  if (demo) {
    const demoText = DEMO[type] || DEMO.full;
    console.log(`🎭 Demo mode requested — type: ${type}`);
    return res.json({ summary: demoText, model: 'Demo Mode', demo: true });
  }

  if (!API_KEY || API_KEY === 'paste_your_api_key_here') {
    // No key set — return demo
    const demoText = DEMO[type] || DEMO.full;
    return res.json({ summary: demoText, model: 'Demo Mode (no API key set)', demo: true });
  }

  if (!text || text.trim().length < 50) {
    return res.status(400).json({ error: 'Text too short. Please provide more content.' });
  }

  const basePrompt = PROMPTS[type] || PROMPTS.full;
  const subjectHint = subject ? `\n\nSubject: ${subject}` : '';
  const fullPrompt = basePrompt + subjectHint + '\n\n---STUDY MATERIAL START---\n' + text.substring(0, 12000) + '\n---STUDY MATERIAL END---';

  console.log(`\n🤖 Summarize request — type: ${type}, subject: ${subject || 'general'}`);

  // Try each model in order
  for (const model of MODELS) {
    console.log(`  → Trying ${model}...`);
    try {
      const result = await tryModel(model, fullPrompt);
      if (result) {
        console.log(`  ✅ Success with ${result.model}`);
        return res.json({ summary: result.text, model: result.model });
      }
    } catch (err) {
      console.log(`  ✗ ${model}: ${err.message}`);
    }
  }

  // All models failed — fall back to demo
  console.log('  ⚠️  All models failed — returning demo response');
  const demoText = DEMO[type] || DEMO.full;
  return res.json({
    summary: demoText,
    model: 'Demo Mode (API quota exceeded)',
    demo: true,
    warning: 'Your Gemini API quota is currently exceeded. Showing demo output. Try again in 24 hours.'
  });
});

// ── Health check ──
app.get('/api/health', (req, res) => {
  const hasKey = API_KEY && API_KEY !== 'paste_your_api_key_here';
  res.json({
    status: 'ok',
    apiKeySet: hasKey,
    message: hasKey ? '✅ Server running with API key set' : '⚠️ Running in Demo Mode (no API key)'
  });
});

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(PORT, () => {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  📚 NoteSnap Backend Server');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`  🚀 Open: http://localhost:${PORT}`);
  if (!API_KEY || API_KEY === 'paste_your_api_key_here') {
    console.log('  🎭 Mode: DEMO (no API key in .env)');
  } else {
    console.log('  ✅ Mode: LIVE (Gemini API key loaded)');
  }
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
});
